#!/usr/bin/env bash

if [[ $(uname) == 'Linux' ]]; then
  sudo apt-get install -y nodejs nodejs-legacy npm

  npm install -g gulp
  npm install
  cd potree
  gulp build

  # cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=../../LAStools/LASzip/build/dll -DLASZIP_LIBRARY=../../LAStools/LASzip/build/src/liblaszip.so ..
elif [[ $(uname) == 'Darwin' ]]; then
  # Install node and gulp
  brew install node
  npm install -g gulp
  npm install

  # Install PotreeConverter
  cd lib/octree
  mkdir -p build
  cd build
  cp ../../../lib/LAStools/LASzip/build/src/liblaszip.dylib
  cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=../../LAStools/LASzip/dll ..
  make
  cd ../../..

  # Install Potree
  cd lib/potree
  npm install
  npm install gulp
  gulp build

  cd ../..
fi

