#!/usr/bin/env bash

if [[ $(uname) == 'Linux' ]]; then
  sudo apt-get install -y nodejs nodejs-legacy npm

  npm install -g gulp
  npm install
  cd potree
  gulp build

elif [[ $(uname) == 'Darwin' ]]; then
  # Install node and gulp
  brew install node cmake boost
  sudo npm install -g gulp nodemon browserify browser-sync
  npm install

  # Install PotreeConverter
  mkdir -p server/build
  cd server/buil
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make
  cd ../..

  # Install Potree
  ./scripts/update
fi

