#!/usr/bin/env bash

if [[ $(uname) == 'Linux' ]]; then
  sudo apt-get install -y nodejs nodejs-legacy npm

  npm install -g gulp
  npm install
  cd potree
  gulp build

  # cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=../../LAStools/LASzip/build/dll -DLASZIP_LIBRARY=../../LAStools/LASzip/build/src/liblaszip.so ..
elif [[ $(uname) == 'Darwin' ]]; then
  # Install node and gulp
  brew install node
  npm install -g gulp
  npm install

  # Install LAStools
  cd lib/LAStools/LASzip
  mkdir -p build
  cd build
  cmake -DCMAKE_BUILD_TYPE=Release ..
  make
  cd ../../../..

  # Install PotreeConverter
  # cd lib/octree
  # mkdir -p build
  # cd build
  # cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=../../LAStools/LASzip/dll -DLASZIP_LIBRARY=../../LAStools/LASzip/build/src/liblaszip.dylib ..
  # make
  # cd ../..

  # Install Potree
  cd lib/potree
  npm install
  npm install gulp
  gulp build

  cd ../..
fi

